# -*- coding: utf-8 -*-
"""returns.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111HAZ9kXkloJlGhiVS2gyHB3yYoD-ot2
"""

import pandas as pd

df = pd.read_csv("/content/ADANIGREEN_with_indicators_.csv", usecols=["date","open"])
print(df.head())

import pandas as pd
from dateutil import parser

# === Step 1: User Input ===
start_input = input("Enter start datetime (e.g., 2018-06-18 14:55:00+05:30): ")
end_input = input("Enter end datetime (e.g., 2018-07-18 14:55:00+05:30): ")

start_dt = parser.parse(start_input)
end_dt = parser.parse(end_input)

# === Step 2: Read the CSV ===
df = pd.read_csv("/content/ADANIGREEN_with_indicators_.csv", usecols=["date","open"], parse_dates=["date"])

# Ensure timestamp column is timezone-aware
df['date'] = pd.to_datetime(df['date'])

# === Step 3: Set timestamp as index ===
df.set_index("date", inplace=True)

# === Step 4: Get Open Prices ===
try:
    price_start = df.loc[start_dt, 'open']
    price_end = df.loc[end_dt, 'open']
except KeyError:
    print("One of the timestamps was not found in the data.")
    exit()

# === Step 5: Calculate Return ===
returns = ((price_end - price_start) / price_start) * 100

print(f"Return from {start_dt} to {end_dt}: {returns:.2f}%")

start_input = input("Enter start datetime (e.g., 2018-06-18 14:55:00+05:30): ")
end_input = input("Enter end datetime (e.g., 2018-07-18 14:55:00+05:30): ")

start_dt = parser.parse(start_input)
end_dt = parser.parse(end_input)

try:
    price_start = df.loc[start_dt, 'open']
    price_end = df.loc[end_dt, 'open']
except KeyError:
    print("One of the timestamps was not found in the data.")
    exit()

returns = ((price_end - price_start) / price_start) * 100

print(f"Return from {start_dt} to {end_dt}: {returns:.2f}%")